### ISSUE TITLE
Props!  But might wanna check patents! :P

### ISSUE THREAD

**Issue by JohnMcLear** [arphid/arphid#1]
Hey guys, I love this project, and I will be happy to support it.

I'm the creator/inventor/maker of the NFC Ring / smart rings and hold a bunch of patents which your implementation is infringing.  We allow you to freely use them all you gotta do is ask :)  

Cheers!

J

**Comment by VegaDeftwing** [comment]
The entire project is open source and DIY and requires that those that want to make it buy seperate componets and assemble it themselevs, and is not a direct competitor to your product. Furthermore making a ring that uses NFC tech is sort of obvious as it is just a convenient placement of a key. I highly doubt your patent would hold if challenged, given that I could literally just glue an NFC tag to a ring and have the same thing.

Furthermore if a total of 33MB infringes on your patent, with the vast majority of that being simple STLs for rings that are capable of storing something (which is definitely not infringing on your patent) then you're saying that the mere idea of putting an NFC tag on a ring breaks your patent. Please, don't sue me if I go glue a tag to a consumed RingPop!

-I have nothing to do with this project, just a bystander that thinks you're a patent troll.

Cheers!

V

**Comment by JohnMcLear** [comment]
@VegaDeftwing YANAL and do not understand patent law.  

Read what I wrote, I'm the exact opposite of a patent troll...  No response required though, you aren't providing anything useful to the conversation.

**Comment by JacobMiske** [comment]
Signed in to upvote VegaDeftwing

**Comment by VegaDeftwing** [comment]
Thanks @JacobMiske ! I realize it's been a year but I never actually saw McLear's reply. I just wanted to put this out there: If @arphid should need any help in court or if you, @JohnMcLear , attempt to get this repository taken down or do anything in any way to enforce a patent in this matter I myself will happily serve as an expert witness or will help procure one even better from the industry. You are without a doubt a patent troll and I again repeat: if you think that your 'invention' is in any way non trival then you are clearly delusional.

Have a great day and either of you, McLear or arphid, feel free to contact me though github or basically anywhere as Vega Deftwing and I will happily speak to multiple lawyers about the matter.

Also we'd all love to get the patent number @JohnMcLear :-)

**Comment by VegaDeftwing** [comment]
I do want to be clear, if you do have a specific, non-pending patent that you can prove is infringed and goes beyond the idea of an NFC capable ring ( Not questioning the validity of your trademark) then I will happily concede, I'm just very hard pressed to see a situation where this could possibly be the case. If there is truly some technical complexity that this project has stolen from you then you have every right to defend your intellectual property. But for you to come in here and blatantly try to scare the project with your cocky attitude is wrong, and I think it was done out of fear of a competing, non infringing product.

**Comment by JohnMcLear** [comment]
Patent number is on USPTO site and nfcring l.com/patents

Fwiw my offer expired as I'm no longer owner of patents.

________________________________
